name: Hank Quinlan, Horrible Cop
markdown: kramdown
url: https://carolinewin.com
repository: https://github.com/wincaroline/wincaroline.github.io
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
